### PR TITLE
scripts: update sed separator to be `,`

### LINKED ISSUE #225: update-deps-in-gomod assumes no slash in base package
While running this in downstream, there is a tiny issue on `sed` which breaks when base package has slashes.

```
        + read -a deps
        + local base_package=tess.io/ebay
        + local dep_count=1
        + local dep_packages=
        + '[' 1 '!=' 0 ']'
        ++ echo api:master
        ++ tr , '\n'
        ++ sed -e 's/:.*//' -e 's/^/tess.io/ebay\//'
        ++ paste -sd , -
        sed: -e expression #2, char 14: unknown option to `s'
        + dep_packages=
E0601 19:23:26.812345      12 publisher.go:413] exit status 1
I0601 19:23:26.815109      12 main.go:202] Failed to run publisher: exit status 1
```

I'd like to propose a fix like this:

```diff
     if [ "$dep_count" != 0 ]; then
-      dep_packages="$(echo ${1} | tr "," "\n" | sed -e 's/:.*//' -e s/^/"${base_package}\/"/ | paste -sd "," -)"
+      dep_packages="$(echo ${1} | tr "," "\n" | sed -e 's/:.*//' -e s~^~"${base_package}/"~ | paste -sd "," -)"
     fi
```

### References

* [How to pass a variable containing slashes to sed][1]

[1]: https://stackoverflow.com/questions/27787536/how-to-pass-a-variable-containing-slashes-to-sed

### PR DESCRIPTION
**Pull request by zhouhaibing089**
`sed -s /^/"${base_package}\/"/` only works when there is no `/`
in `${base_package}`. While this is true for `k8s.io`, this is not
necessary true for downstream repositories.

Here is the error message when `${base_package}` is `tess.io/ebay`:

```console
        ++ echo api:master
        ++ tr , '\n'
        ++ sed -e 's/:.*//' -e 's/^/tess.io/ebay\//'
        ++ paste -sd , -
        sed: -e expression #2, char 14: unknown option to `s'
        + dep_packages=
E0601 19:23:26.812345      12 publisher.go:413] exit status 1
I0601 19:23:26.815109      12 main.go:202] Failed to run publisher: exit status 1
```

Fixes #225.

### CODE REVIEW

File: artifacts/scripts/util.sh [hunk 1]
```diff
@@ -851,7 +851,7 @@ update-deps-in-gomod() {
     # if dependencies exist, dep_packages is a comma separated list of {base_package}/{dep}. Eg: "k8s.io/api,k8s.io/apimachinery"
     local dep_packages=""
     if [ "$dep_count" != 0 ]; then
-      dep_packages="$(echo ${1} | tr "," "\n" | sed -e 's/:.*//' -e s/^/"${base_package}\/"/ | paste -sd "," -)"
+      dep_packages="$(echo ${1} | tr "," "\n" | sed -e 's/:.*//' -e s~^~"${base_package}/"~ | paste -sd "," -)"
```
Comment (sttts) [inline artifacts/scripts/util.sh:854]: I think elsewhere we use comma. Tilde is used in bash. Am not so confortable to use that.

Comment (zhouhaibing089) [reply artifacts/scripts/util.sh]: Thanks, I updated it to be `,`. Tested with:

```console
$ echo api:master | tr "," "\n" | sed -e 's/:.*//' -e 's,^,tess.io/ebay/,'
tess.io/ebay/api
```
